### ISSUE TITLE
Compiling with -pedantic and -Wextra leads to a lot of warnings

### ISSUE THREAD

**Issue by stevemolloy** [forkachild/C-Simple-JSON-Parser#20]
When compiling with -pedantic and -Wextra I see a lot of warnings.  Some of these are trivial (like the missing newline at the end of the .h file), but others seem more involved.  For example, `cast to union type is a GNU extension`.

I'd like to get rid of the warnings so that my project compiles cleanly, but am unsure if there is something about this project that means that these will be hard to remove.

Any comments?

**Comment by whyisitworking** [comment]
@stevemolloy They are quite simple fixes I believe. Would you mind taking this up and raising a PR?

**Comment by stevemolloy** [comment]
I can take this.  Give me a bit, and I will come back with a PR.

**Comment by stevemolloy** [comment]
Do you have any tests I could use?  Except for example.c?

**Comment by whyisitworking** [comment]
There are no tests for this yet. I'll add them. Can you raise an issue for that?
