### ISSUE TITLE
Value numbers

### ISSUE THREAD

**Issue by Rokscript08** [forkachild/C-Simple-JSON-Parser#3]
Hey, 
First of all, love your coding!! I just found one issue, what happens when the value is a (float/double/int) number instead of a string. If you fix it please let me know.

Thanks for your work.

**Comment by whyisitworking** [comment]
Hi,

Thanks for appreciating my work and also for pointing out the issue. I will
fix it soon and let you know.

**Comment by ajita-01** [comment]
Hey,

Thanks for the great code and work. I was curious to know if this issue with value as numbers has been solved. One more question can I use, edit code and reuse it anywhere. I could not find any liscense agreement as such. Huge thanks in advance

**Comment by whyisitworking** [comment]
Hi,

I'm really sorry for not being able to dedicate time to this, it hasn't been fixed yet. There is no license agreement, feel free to do anything you want with this. If possible can you fix the issue and create a PR?
